import type { Domain } from "@prisma/client";

export interface ConceptSeed {
  id: string;
  domain: Domain;
  label: string;
  description: string;
  sequence: number;
  learningObjectives: string[];
  commonMisconceptions: string[];
  diagnosticQuestions: string[];
  teachingStrategies: string[];
  examples: string[];
  masteryCriteria: string;
  retentionIntervalDays: number;
}

export const CONCEPTS: ConceptSeed[] = [
  // ─── MATH ──────────────────────────────────────────────────────────────────
  {
    id: "counting_to_20",
    domain: "MATH",
    label: "Counting to 20",
    description: "Reciting and using the count sequence to 20 with one-to-one correspondence.",
    sequence: 10,
    learningObjectives: [
      "Recite number names in order to 20",
      "Count a set of objects with one-to-one correspondence",
      "Know that the last number counted tells how many (cardinality)",
    ],
    commonMisconceptions: [
      "Recites the sequence but does not map one number to one object",
      "Recounts from one when asked 'how many' (no cardinality)",
      "Skips the teens, especially 13-15",
    ],
    diagnosticQuestions: [
      "Can you count these seven counters out loud for me?",
      "You just counted them. So how many are there altogether?",
      "What number comes right after 12?",
    ],
    teachingStrategies: ["counters", "touch_counting", "number_line", "rhythm_chant"],
    examples: ["Count 7 dinosaurs", "What comes after 15?"],
    masteryCriteria: "Counts a set of up to 20 accurately and answers 'how many' without recounting.",
    retentionIntervalDays: 14,
  },
  {
    id: "number_magnitude",
    domain: "MATH",
    label: "Number magnitude",
    description: "Comparing quantities and knowing which of two numbers is larger.",
    sequence: 20,
    learningObjectives: ["Compare two numbers within 20", "Place a number roughly on a 0-20 line"],
    commonMisconceptions: [
      "Judges size by the digit shape or length of the spoken word",
      "Believes a later-counted number is 'better' rather than larger",
    ],
    diagnosticQuestions: ["Which is bigger, 8 or 12?", "Is 14 closer to 10 or closer to 20?"],
    teachingStrategies: ["number_line", "counters", "comparison_stories"],
    examples: ["Which pile has more?", "Put 13 on the number line"],
    masteryCriteria: "Compares any two numbers within 20 and justifies with quantity, not digits.",
    retentionIntervalDays: 14,
  },
  {
    id: "addition_within_10",
    domain: "MATH",
    label: "Addition within 10",
    description: "Combining two quantities with a total of 10 or less.",
    sequence: 30,
    learningObjectives: ["Add two single-digit numbers within 10", "Count on from the larger addend"],
    commonMisconceptions: [
      "Always counts all from one instead of counting on",
      "Loses track of the count when using fingers",
    ],
    diagnosticQuestions: ["What is 3 + 4?", "How did you work that out?", "What is 2 + 6?"],
    teachingStrategies: ["counters", "count_on", "number_line", "story_framing"],
    examples: ["3 cookies plus 2 more", "4 + 5"],
    masteryCriteria: "Adds within 10 accurately and can explain the strategy used.",
    retentionIntervalDays: 10,
  },
  {
    id: "subtraction_within_10",
    domain: "MATH",
    label: "Subtraction within 10",
    description: "Taking away or finding the difference within 10.",
    sequence: 40,
    learningObjectives: ["Subtract within 10", "Understand subtraction as both take-away and difference"],
    commonMisconceptions: [
      "Subtracts the smaller number from the larger regardless of order",
      "Treats subtraction as always meaning 'count backwards one at a time'",
    ],
    diagnosticQuestions: ["What is 7 - 3?", "How did you get that?", "What is 9 - 6?"],
    teachingStrategies: ["counters", "number_line", "take_away_story", "count_back"],
    examples: ["7 grapes, eat 3", "9 - 4"],
    masteryCriteria: "Subtracts within 10 accurately with a stated strategy.",
    retentionIntervalDays: 10,
  },
  {
    id: "addition_within_20",
    domain: "MATH",
    label: "Addition within 20",
    description: "Adding with totals up to 20, including bridging through ten.",
    sequence: 50,
    learningObjectives: ["Add within 20", "Use make-ten strategies to bridge the decade"],
    commonMisconceptions: [
      "Counts on by ones instead of bridging through ten",
      "Miscounts the teens when crossing 10",
    ],
    diagnosticQuestions: ["What is 8 + 5?", "How did you figure that out?", "What is 9 + 7?"],
    teachingStrategies: ["make_ten", "number_line", "ten_frame", "counters"],
    examples: ["8 + 5 by making ten", "9 + 7"],
    masteryCriteria: "Adds within 20 including bridging ten, with a reasoned strategy.",
    retentionIntervalDays: 7,
  },
  {
    id: "subtraction_within_20",
    domain: "MATH",
    label: "Subtraction within 20",
    description: "Subtracting within 20 where the problem does not require crossing ten.",
    sequence: 60,
    learningObjectives: ["Subtract within 20 without regrouping", "Explain the strategy used"],
    commonMisconceptions: [
      "Counts back inaccurately, off by one",
      "Confuses subtraction with addition when the language is unfamiliar",
    ],
    diagnosticQuestions: ["What is 17 - 6?", "What is 18 - 7?", "How did you work it out?"],
    teachingStrategies: ["number_line", "count_back", "ten_frame", "counters"],
    examples: ["17 - 6", "19 - 4"],
    masteryCriteria: "Subtracts within 20 without crossing ten, accurately and with explanation.",
    retentionIntervalDays: 7,
  },
  {
    id: "cross_ten_subtraction",
    domain: "MATH",
    label: "Cross-ten subtraction",
    description: "Subtracting where the answer requires moving back across a ten boundary, e.g. 17 - 9.",
    sequence: 70,
    learningObjectives: [
      "Subtract across a ten boundary within 20",
      "Decompose the subtrahend to reach ten first",
      "Track position while counting back across ten",
    ],
    commonMisconceptions: [
      "Treats the digits independently, subtracting the smaller digit from the larger in each column (answers 17 - 9 as 10 by computing 9 - 7 then reattaching the 1)",
      "Loses track of the count when crossing ten, landing one off",
      "Stops at ten and forgets to continue subtracting the remainder",
      "Reverses the operands to avoid crossing ten",
    ],
    diagnosticQuestions: [
      "What is 17 - 9?",
      "Can you show me how you got that?",
      "What about 15 - 8?",
      "If we start at 17 and count backwards 9 steps, where do we land?",
    ],
    teachingStrategies: ["number_line", "decompose_to_ten", "ten_frame", "counters", "count_back"],
    examples: ["17 - 9 by going to 10 first, then back 2 more", "15 - 8", "32 - 7"],
    masteryCriteria:
      "Subtracts across ten in varied problem forms, independently, with correct reasoning, and retains it after a delay.",
    retentionIntervalDays: 5,
  },
  {
    id: "place_value_tens_ones",
    domain: "MATH",
    label: "Place value: tens and ones",
    description: "Understanding two-digit numbers as tens and ones.",
    sequence: 80,
    learningObjectives: ["Decompose a two-digit number into tens and ones", "Explain what each digit means"],
    commonMisconceptions: [
      "Reads 34 as 'three and four' rather than three tens and four ones",
      "Believes the left digit is simply 'the bigger one'",
    ],
    diagnosticQuestions: ["In the number 34, what does the 3 mean?", "How many tens are in 47?"],
    teachingStrategies: ["base_ten_blocks", "bundling_sticks", "place_value_chart"],
    examples: ["34 = 3 tens and 4 ones"],
    masteryCriteria: "Decomposes any two-digit number and explains each digit's value.",
    retentionIntervalDays: 7,
  },

  // ─── READING ───────────────────────────────────────────────────────────────
  {
    id: "letter_recognition",
    domain: "READING",
    label: "Letter recognition",
    description: "Naming upper and lowercase letters quickly and accurately.",
    sequence: 10,
    learningObjectives: ["Name all 26 letters in both cases", "Distinguish visually similar letters"],
    commonMisconceptions: ["Confuses b/d/p/q", "Confuses letter name with letter sound"],
    diagnosticQuestions: ["What letter is this?", "Can you find the letter that makes the /m/ sound?"],
    teachingStrategies: ["letter_cards", "tracing", "highlight_word", "alphabet_song"],
    examples: ["Identify b vs d"],
    masteryCriteria: "Names all letters in both cases without hesitation.",
    retentionIntervalDays: 14,
  },
  {
    id: "phonemic_awareness",
    domain: "READING",
    label: "Phonemic awareness",
    description: "Hearing and manipulating individual sounds in spoken words.",
    sequence: 20,
    learningObjectives: ["Identify initial, medial, final sounds", "Blend and segment phonemes"],
    commonMisconceptions: [
      "Segments by syllable instead of phoneme",
      "Cannot isolate a medial vowel sound",
    ],
    diagnosticQuestions: ["What sound does 'cat' start with?", "What sounds do you hear in 'sun'?"],
    teachingStrategies: ["sound_boxes", "oral_blending", "rhyming_games"],
    examples: ["/s/ /u/ /n/ makes sun"],
    masteryCriteria: "Blends and segments three-phoneme words reliably.",
    retentionIntervalDays: 10,
  },
  {
    id: "cvc_decoding",
    domain: "READING",
    label: "CVC decoding",
    description: "Sounding out consonant-vowel-consonant words.",
    sequence: 30,
    learningObjectives: ["Decode unfamiliar CVC words", "Blend sounds left to right"],
    commonMisconceptions: [
      "Guesses the word from the first letter and picture cues",
      "Sounds each letter but cannot blend them",
    ],
    diagnosticQuestions: ["Can you read this word: 'mat'?", "How did you work it out?"],
    teachingStrategies: ["sound_it_out", "highlight_word", "blending_slide"],
    examples: ["mat, pin, dog"],
    masteryCriteria: "Decodes unfamiliar CVC words without picture support.",
    retentionIntervalDays: 7,
  },
  {
    id: "sight_words",
    domain: "READING",
    label: "Sight words",
    description: "Instant recognition of high-frequency irregular words.",
    sequence: 40,
    learningObjectives: ["Recognise common sight words instantly"],
    commonMisconceptions: ["Tries to decode irregular words phonetically", "Confuses was/saw, on/no"],
    diagnosticQuestions: ["What is this word: 'the'?", "And this one: 'said'?"],
    teachingStrategies: ["flash_recognition", "highlight_word", "sentence_context"],
    examples: ["the, said, was, come"],
    masteryCriteria: "Reads common sight words instantly without decoding.",
    retentionIntervalDays: 7,
  },
  {
    id: "sentence_comprehension",
    domain: "READING",
    label: "Sentence comprehension",
    description: "Understanding and retelling the meaning of a sentence.",
    sequence: 50,
    learningObjectives: ["Retell a sentence in own words", "Answer who/what/where questions"],
    commonMisconceptions: [
      "Decodes accurately but retains no meaning",
      "Repeats the sentence verbatim instead of retelling",
    ],
    diagnosticQuestions: ["What happened in that sentence?", "Who was it about?"],
    teachingStrategies: ["show_story", "retell_prompt", "picture_support"],
    examples: ["The dog ran to the park."],
    masteryCriteria: "Retells sentence meaning in own words and answers comprehension questions.",
    retentionIntervalDays: 7,
  },

  // ─── REASONING ─────────────────────────────────────────────────────────────
  {
    id: "evidence_giving",
    domain: "REASONING",
    label: "Giving evidence",
    description: "Supporting a claim with a reason rather than restating it.",
    sequence: 10,
    learningObjectives: ["Offer a reason for an opinion", "Distinguish a reason from a restatement"],
    commonMisconceptions: ["Restates the claim as the reason", "Appeals only to personal preference"],
    diagnosticQuestions: ["Why do you think that?", "What makes you say so?"],
    teachingStrategies: ["because_prompt", "story_framing", "socratic_followup"],
    examples: ["I think it will float because it is light."],
    masteryCriteria: "Gives a genuine reason distinct from the claim itself.",
    retentionIntervalDays: 14,
  },
  {
    id: "counterexample_finding",
    domain: "REASONING",
    label: "Finding counterexamples",
    description: "Identifying a case that disproves a general claim.",
    sequence: 20,
    learningObjectives: ["Recognise an overgeneralisation", "Produce a counterexample"],
    commonMisconceptions: [
      "Agrees with any confidently stated general claim",
      "Offers an example that supports rather than refutes",
    ],
    diagnosticQuestions: [
      "Sarah says every animal with wings can fly. Is she right?",
      "Can you think of something with wings that cannot fly?",
    ],
    teachingStrategies: ["counterexample_hunt", "story_framing", "category_sorting"],
    examples: ["Penguins and ostriches have wings but cannot fly."],
    masteryCriteria: "Produces a valid counterexample to an overgeneralised claim.",
    retentionIntervalDays: 14,
  },
  {
    id: "belief_updating",
    domain: "REASONING",
    label: "Updating a belief",
    description: "Changing a conclusion when new facts arrive.",
    sequence: 30,
    learningObjectives: ["Revise an answer given new information", "Say what changed their mind"],
    commonMisconceptions: [
      "Holds the original answer despite contradicting evidence",
      "Switches answers without being able to say why",
    ],
    diagnosticQuestions: ["Does that change what you thought?", "What made you change your mind?"],
    teachingStrategies: ["new_fact_reveal", "socratic_followup", "story_framing"],
    examples: ["Revising 'all birds fly' after meeting a penguin."],
    masteryCriteria: "Updates a conclusion on new evidence and articulates the reason.",
    retentionIntervalDays: 14,
  },
  {
    id: "categorical_claims",
    domain: "REASONING",
    label: "All / some / none",
    description: "Reasoning carefully about quantifiers in claims.",
    sequence: 40,
    learningObjectives: ["Distinguish 'all' from 'some'", "Notice when a claim is too strong"],
    commonMisconceptions: ["Treats 'some' and 'all' as interchangeable", "Over-applies a rule learned from one case"],
    diagnosticQuestions: ["Do ALL dogs have spots, or do SOME dogs have spots?"],
    teachingStrategies: ["category_sorting", "counterexample_hunt", "venn_picture"],
    examples: ["Some dogs have spots; not all do."],
    masteryCriteria: "Correctly distinguishes universal from existential claims.",
    retentionIntervalDays: 14,
  },
  {
    id: "explanation_quality",
    domain: "REASONING",
    label: "Explaining thinking",
    description: "Describing the steps taken to reach an answer.",
    sequence: 50,
    learningObjectives: ["Narrate a solution process", "Identify where thinking went wrong"],
    commonMisconceptions: ["Says only 'I just knew it'", "Describes the answer rather than the route to it"],
    diagnosticQuestions: ["How did you figure that out?", "What did you do first?"],
    teachingStrategies: ["think_aloud", "socratic_followup", "step_replay"],
    examples: ["First I went to ten, then I took away two more."],
    masteryCriteria: "Describes a multi-step process in order, unprompted.",
    retentionIntervalDays: 10,
  },
];
