-- CreateEnum
CREATE TYPE "SentinelActionType" AS ENUM ('SCAN_CONNECTOR','IMPORT_DOCUMENTS','SYNTHESIZE_WORKSPACE','GENERATE_OPPORTUNITIES','GENERATE_TICKETS','PUSH_TO_LINEAR','SYNC_LINEAR_STATUS','GENERATE_DIGEST');
CREATE TYPE "SentinelActionStatus" AS ENUM ('PENDING_REVIEW','APPROVED','EXECUTING','COMPLETED','REJECTED','FAILED');

-- CreateTable SentinelAction
CREATE TABLE "SentinelAction" (
  id TEXT PRIMARY KEY,
  "workspaceId" TEXT NOT NULL,
  type "SentinelActionType" NOT NULL,
  status "SentinelActionStatus" NOT NULL DEFAULT 'PENDING_REVIEW',
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  payload JSONB NOT NULL,
  result JSONB,
  "triggeredBy" TEXT NOT NULL DEFAULT 'system',
  "reviewedAt" TIMESTAMP(3),
  "executedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("workspaceId") REFERENCES "Workspace"(id) ON DELETE CASCADE
);

-- CreateTable WorkspaceSettings
CREATE TABLE "WorkspaceSettings" (
  id TEXT PRIMARY KEY,
  "workspaceId" TEXT UNIQUE NOT NULL,
  "autoSynthesizeOnIngest" BOOLEAN NOT NULL DEFAULT false,
  "autoImportHighScore" BOOLEAN NOT NULL DEFAULT false,
  "autoPushToLinear" BOOLEAN NOT NULL DEFAULT false,
  "digestFrequency" TEXT NOT NULL DEFAULT 'weekly',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("workspaceId") REFERENCES "Workspace"(id) ON DELETE CASCADE
);
