import { FadeUp } from './FadeUp'

export function ProductOverview() {
  return (
    <section className="max-w-6xl mx-auto px-6 py-20 border-t border-border">
      <FadeUp>
        <div className="text-center mb-14">
          <p className="text-xs font-semibold text-brand uppercase tracking-widest mb-3">Product</p>
          <h2 className="text-3xl md:text-4xl font-semibold text-foreground tracking-tight">
            Everything your PM wishes existed
          </h2>
          <p className="text-sm text-muted-foreground mt-3 max-w-lg mx-auto">
            Sentinel doesn&apos;t just help you manage — it manages for you.
          </p>
        </div>
      </FadeUp>

      <div className="grid md:grid-cols-3 gap-6">
        {/* Feature 1: Autonomous inbox */}
        <FadeUp delay={0}><div className="rounded-xl border border-border p-5 bg-card flex flex-col gap-4 hover:border-brand/30 transition-colors h-full">
          <div>
            <h3 className="text-sm font-semibold text-foreground mb-1.5">Autonomous inbox</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Sentinel queues actions for your review. One click to approve — it handles the execution.
            </p>
          </div>
          <div className="mt-auto space-y-2">
            {[
              { label: 'Create ENG-042 from insight', badge: 'Pending' },
              { label: 'Sync opportunity to Linear', badge: 'Pending' },
              { label: 'Draft PRD: Onboarding v2', badge: 'Approved' },
            ].map(item => (
              <div key={item.label} className="flex items-center justify-between px-3 py-2 rounded-lg bg-background border border-border">
                <span className="text-xs text-foreground truncate mr-2">{item.label}</span>
                <span className={`text-[10px] font-medium px-2 py-0.5 rounded-full flex-shrink-0 ${
                  item.badge === 'Approved'
                    ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-400'
                    : 'bg-amber-100 text-amber-700 dark:bg-amber-950/40 dark:text-amber-400'
                }`}>
                  {item.badge}
                </span>
              </div>
            ))}
          </div>
        </div></FadeUp>

        {/* Feature 2: Semantic search */}
        <FadeUp delay={80}><div className="rounded-xl border border-border p-5 bg-card flex flex-col gap-4 hover:border-brand/30 transition-colors h-full">
          <div>
            <h3 className="text-sm font-semibold text-foreground mb-1.5">Semantic search</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Ask anything across all your ingested documents. pgvector-powered similarity search.
            </p>
          </div>
          <div className="mt-auto space-y-2">
            <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-background border border-border">
              <span className="text-muted-foreground text-xs">⌕</span>
              <span className="text-xs text-muted-foreground">What are users saying about onboarding?</span>
            </div>
            {['User interview — Jul 2024', 'Support ticket #1482', 'NPS survey Q2'].map(r => (
              <div key={r} className="px-3 py-2 rounded-lg bg-muted/50 border border-border">
                <p className="text-xs text-foreground">{r}</p>
              </div>
            ))}
          </div>
        </div></FadeUp>

        {/* Feature 3: Linear sync */}
        <FadeUp delay={160}><div className="rounded-xl border border-border p-5 bg-card flex flex-col gap-4 hover:border-brand/30 transition-colors h-full">
          <div>
            <h3 className="text-sm font-semibold text-foreground mb-1.5">Linear sync</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Tickets generated by Sentinel push directly to your Linear workspace — with proper priority, labels, and estimates.
            </p>
          </div>
          <div className="mt-auto space-y-2">
            {[
              { id: 'ENG-041', title: 'Auth system redesign', status: 'In Progress' },
              { id: 'ENG-042', title: 'Streamline onboarding', status: 'Backlog' },
              { id: 'ENG-043', title: 'API rate limiting', status: 'Backlog' },
            ].map(t => (
              <div key={t.id} className="flex items-center gap-2 px-3 py-2 rounded-lg bg-background border border-border">
                <span className="text-[10px] text-muted-foreground font-mono">{t.id}</span>
                <span className="text-xs text-foreground flex-1 truncate">{t.title}</span>
                <span className={`text-[10px] flex-shrink-0 ${t.status === 'In Progress' ? 'text-brand' : 'text-muted-foreground'}`}>
                  {t.status}
                </span>
              </div>
            ))}
          </div>
        </div></FadeUp>
      </div>
    </section>
  )
}
